name: base
channels:
  - defaults
dependencies:
  - _anaconda_depends
  - python=3.13
  - setuptools
  - pip
  - wheel
  - anaconda-anon-usage
  - anaconda-catalogs
  - anaconda-client
  - anaconda-project
  - anaconda-navigator
  - conda
  - conda-anaconda-telemetry
  - conda-anaconda-tos[version='>=0.2.0']
  - conda-build
  - conda-content-trust
  - conda-libmamba-solver
  - conda-pack
  - conda-package-handling
  - conda-package-streaming
  - anaconda-auth
  - python.app
  - anaconda-toolbox
  - numpy
  - pandas
